### ISSUE TITLE
won't install

### ISSUE THREAD

**Issue by jtc25** [skelterjohn/go-gb#19]
Make install yields the following message:
6g -I ./_obj  -o _go_.6 build.go cgo.go deps.go files.go gb.go genmake.go gentest.go gofmt.go goinstall.go make.go pkg.go query.go runext.go usage.go util.go 
genmake.go:72: assignment count mismatch: 2 = 1
genmake.go:125: assignment count mismatch: 2 = 1
gentest.go:121: assignment count mismatch: 2 = 1
make: **\* [_go_.6] Error 1
 I have a Imac OSX 10.7.

**Comment by skelterjohn** [comment]
This is what happens when the version of Go doesn't match the version of gb.

If you are using the release version of go, checkout the release version of gb (git checkout release).

If you're using the weekly go, checkout the master branch of gb (git checkout master).

If you're using something else, then you're S.O.L. :)
