### ISSUE TITLE
Can't Install

### ISSUE THREAD

**Issue by HamptonMakes** [skelterjohn/go-gb#21]
When I run...

```
sudo -E goinstall go-gb.googlecode.com/hg/gb
```

The installation fails with the following messages

```
/bin/bash: === cd /usr/local/Cellar/go/r59/src/pkg/go-gb.googlecode.com/hg/gb; bash gomake -f- install
6g -I "/usr/local/Cellar/go/r59/pkg/darwin_amd64"  -o _go_.6 build.go cgo.go deps.go files.go gb.go genmake.go gentest.go gofmt.go goinstall.go make.go pkg.go query.go runext.go usage.go util.go 
genmake.go:38: cannot use "MakeCmd" (type string) as type template.FormatterMap in function argument
genmake.go:71: assignment count mismatch: 2 = 1
genmake.go:78: cannot use "MakePkg" (type string) as type template.FormatterMap in function argument
genmake.go:124: assignment count mismatch: 2 = 1
gentest.go:85: cannot use "testmain" (type string) as type template.FormatterMap in function argument
gentest.go:121: assignment count mismatch: 2 = 1
make: *** [_go_.6] Error 1
--- exit status 2
goinstall: go-gb.googlecode.com/hg/gb: install: running bash: exit status 2
```

Halp!

**Comment by skelterjohn** [comment]
Hi,

Since r60, goinstall has the ability to match the go version to the version of what you're installing. Unfortunately if you're using r59 (which I gather you are from the file paths I see), goinstall will just grab the "release" tag. For gb, the current release tag matches r60.1.

Would it be an inconvenience to switch to r60.1? From then on this shouldn't be a problem anymore, even if you want to remain at r60.1 instead of going forward with other releases, because I have a tag "go.r60.1" in the repository.

Otherwise the easiest way to do it might be just fixing those compile errors.

To fix the "cannot use" errors, replace the literal string with nil.

To fix the "assignment count" errors, either delete the 2nd argument (if it should be 1 argument) or add an argument that is just nil (if it should be 2 arguments).
- John

**Comment by HamptonMakes** [comment]
Yeah! Fixed!

Maybe throw a message for versions before? If its undefined, then it means its before that version right?
