### ISSUE TITLE
Support for setting same target for files in different directories

### ISSUE THREAD

**Issue by ashokgelal** [skelterjohn/go-gb#22]
I don't know what I want is even remotely possible with gb. But here is what I'm looking for:

my directory structure
`src`
`|--- cmd`
`|    |--- main.go`
`|--- pkg`
`|--- foo`
`|     |--- file1.go`
`|--- bar`
`|     |--- file2.go`

My requirement is that I want to have **file1.go** and **file2.go** in same package. I have some reasons for this directory layout. I tried setting **//target: mylib/all** on both **file1.go** and **file2.go** but I get **Duplicate Target** error. 
Am I missing something or this is not supported by gb? If not, is there a chance to support something like this in near future?

Other than this, gb works great.

**Comment by skelterjohn** [comment]
You aren't missing anything - there is currently no way to do this. Nor do I
have plans to allow it.

Might I ask why you need this kind of structure?

**Comment by ashokgelal** [comment]
It is hard to explain and I cannot disclose all the details (legal issues) but my app needs to put files in different directories and at the end combine them all. I have a make file do but it is way complicated. I like the way gb does all the compilation for you. I was thinking to use gb as a must and default tool for compiling this project. As far as I see, this project is going to be a big one and I was hoping that by making gb as a default make tool, it is going to be good for both the project (regarding handling makefile complexity) and for gb itself (regarding more people using it).

Do you know any other tool that might do the job for me? I tried godag but it is not as easy as gb.

**Comment by skelterjohn** [comment]
godag has the same requirements (I'm pretty sure). This req of all target
source being in one folder isn't my idea - it is also how goinstall works.
It is also how the future "go build" will work.

If it's the writing of the makefiles that bothers you (rather than the using
of them), you can run "gb --makefiles" and it will create a set of makefiles
and build script to invoke them. The build script/makefiles will do
incremental building just like gb does. Then you can go in and add the file
../bar/file2.go to foo's makefile.
- John
