### ISSUE TITLE
Doesn't create workspace.gb in intermediate (target-less) directories.

### ISSUE THREAD

**Issue by bmatsuo** [skelterjohn/go-gb#25]
I have a directory structure _[package names have been changed to protect the innocent]_

```
./
    mypkg/
        mypkg.go
    myextension/
        myextension.go
    examples/
        pkg-example/
              example.go
        extension-example/
              example.go
        utils/
              utils.go
```

When I run `gb --workspace` (from the working directory `./`), workspace.gb files are created in all subdirectories except for `examples/`. And, it makes building from `examples/` impossible because the files `examples/*-example/example.go` use the import path `"examples/utils"`.

Please have `gb` create these workspace.gb files.

Thanks in advance. The fact that it builds so easily at all is a wonder ;)

Cheers

**Comment by skelterjohn** [comment]
This is reasonable, although not trivial (gb adds a workspace.gb for each "active" target, rather than traversing the file tree).

I'll do something about it, though I've been thinking of wrapping up all the different kinds of .gb files (target.gb, workspace.gb, atm) into one gb.cfg (with a line workspace=, target= etc), and I might role it into one change.

**Comment by bmatsuo** [comment]
Cool. Thanks for thinking about it.

**Comment by skelterjohn** [comment]
actually, it was a trivial fix. i was already adding the workspace.gb files while searching the file tree (not by iterating the packages).

now --workspace creates (or adds to) a gb.cfg in each listed directory and their subdirectories. I'll update the docs about gb.cfg soon.

**Comment by bmatsuo** [comment]
Glad it was so easy =)
